### ISSUE TITLE
Message signature created by sign_osx differs from the one created by sign_linux

### ISSUE THREAD

**Issue by simonerom** [iotexproject/pebble-simulator#21]
running simulator.sh on OSX provides the wrong signature for the data messages. E.g. given the following private key and data message:
```bash
Private key: 5d56e6f6313e932093b9f1ad1a4939ee0cf00c14649527252e58378d20e207fb 

Data message: {"message":{"snr":163,"vbat":4.20419,"latitude":7345.88596,"longitude":8324.76404,"gasResistance":450,"temperature":9.28537,"pressure":334.95856,"humidity":22.77893,"light":1639.67767,"temperature2":73.81049,"gyroscope":[-762,-7,8],"accelerometer":[762,1040,1317],"timestamp":"150000","random":"e26338bafd95137a"}}
```

the signature on macOS returns:
```
r: 0x0xf67ffef2f055e6351f54976d89ee66b69b9a1bbdea368d03e21e8f8495948f86
s: 0x30a3aa31dcaab46b91b1568fb0a3542655b54e7242364de9ef35f893e3d1f5a8
v: 01
```

while the signature on ubuntu returns:
```
r: 0x45c80286b9583831834e411c42dee59d74efb7c39adee0655ff9051048dcc9d2
s: 0x15cb1e6d9d513a13d079acb20aaf21a65f5aa2ea6173b4dbe540663049b9d9f8
v: 00
```

When verifying with:
```solidity
contract testVerify {
...
messageHash = keccak256(bytes(message));
address = ecrecover(messageHash, v+27, r, s);
```
the signature obtained on Linux **can be correctly verified** (`ecrecover` returns an address that matches the simulator private key), while the signature obtained on macOS cannot be verified (`ecrecover` returns a non-zero address, but the wrong one)

**Comment by Tide00** [comment]
Just because sign_osx uses sha256 and sign_linux uses Keccak256Hash. Now they both use the same hash function Keccak256Hash.
